### ISSUE TITLE
Add message to indicate that user table can only be viewed on the web

### ISSUE THREAD

**Issue by acekyd** [acekyd/devcenter-social#3]

**Comment by shalvah** [comment]
Apparently, this has been done. But why restrict the table to web only?

**Comment by acekyd** [comment]
You are right @shalvah It's been done. The major reason was tabular data on mobile phones... I'm sure there would be ways around it though... Open to pull requests :)

**Comment by shalvah** [comment]
Before this was done, clicking on the table button launched Google Sheets app. When I didn't have the app installed, it still showed up okay on web.

**Comment by shalvah** [comment]
Oh... Just checked out the site on desktop... Looks like you're no longer using Google Sheets... Which is quite cool. The UI looks awesome now.
But that means making it available mobile is a bigger task.

**Comment by acekyd** [comment]
@shalvah... Still using Google Sheets... I'm using a library to access the data so it really does feel open-sourcey lol... Please give it a try if it interests you :)
