### ISSUE TITLE
Add a link to the original google doc document

### ISSUE THREAD

**Issue by acekyd** [acekyd/devcenter-social#4]
Here's the link https://docs.google.com/spreadsheets/d/1FUKXOS0KRGDy5gXyFPrOT6uXUexfeMyLlSk2QYbL2Ks/edit#gid=0

**Comment by captbrogers** [comment]
I can help with this, where would you like the link to be and what text would you like to have for the link? Also, if you wouldn't mind assigning it to me so I can get notifications for it.

**Comment by ekpo-d** [comment]
@captbrogers thanks for showing interest. The link should be displayed after the user has signed in, below the DC logo.
Text - 'you can also view the google doc' or anything creative. Also, the link should follow the color theme :)

**Comment by captbrogers** [comment]
@ekpo-d Sounds good, I'll get on it.
