### ISSUE TITLE
Add a paragraph after the 'Welcome' paragraph.

### ISSUE THREAD

**Issue by ekpo-d** [acekyd/devcenter-social#6]
Th paragraph to be added should be a short description of the purpose of the devcenter-social app.

**Comment by atomtigerzoo** [comment]
Hi! I would add this short paragraph of warm welcoming, if I knew what this app is all about :) The description on your page and the repo is a bit short. Can you give me some hints?

**Comment by acekyd** [comment]
Hello @atomtigerzoo The app is built to automate following on github among members of a small developer community. So interested persons visit the link and click on the button to join the follow train. Hope that helps.

**Comment by atomtigerzoo** [comment]
Ok - I will think about a short introduction. With 'Welcome' paragraph [line 44](https://github.com/acekyd/devcenter-social/blob/14a6f7a658d941dca69e87b6c4a33ecb6844c9df/resources/views/welcome.blade.php#L44) in `welcome.blade.php` was meant, right?

**Comment by acekyd** [comment]
Yes @atomtigerzoo :)

**Comment by atomtigerzoo** [comment]
Here some ideas, ready for discussion and moving around to get a nice intro :)

---

**Welcome to our repository|community|group!**
Connect to all contributors with a simple click of a button! 
Keep up with requests, issues and discussions in our repository.

---

**Keep up to date with your repo!**
Connect to all contributors with a simple click - just login with github.
Follow the community, stay informed and get connected!

---

**Stay|Get connected**
Connect with the contributors, stay informed and follow the news!
Simply login with github and keep connected!

**Comment by ekpo-d** [comment]
@atomtigerzoo the last option seems the best fit, the heading - 'Get connected' - seems best also.
