### ISSUE TITLE
Reduce the length of the 'join and follow' CTA button.

### ISSUE THREAD

**Issue by ekpo-d** [acekyd/devcenter-social#7]
The text of the 'join and follow' button is quite long - shorten it :). Also, be creative about it.

**Comment by atomtigerzoo** [comment]
I would get rid of one of the join/follow words only, maybe keep the length somehow. Here are some ideas: "Join X users" / "Connect with X users" / "Follow X users" / "Discover X friendly users" or another lengthy one "Join to follow X users". Anything you like?

**Comment by acekyd** [comment]
I think "Connect with X users" would do fine @atomtigerzoo
